import { writeFile, readFile, appendFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

const VAULT_PEOPLE_DIR = "C:\\Users\\vhaug\\second brain\\02-knowledge\\people";
const VAULT_INDEX = path.join(VAULT_PEOPLE_DIR, "INDEX.md");

export async function POST(req: Request) {
  const { target, rawText, date } = await req.json();

  if (!target || !rawText) {
    return Response.json({ error: "Missing target or rawText" }, { status: 400 });
  }

  const slug = target.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const filename = `${slug}.md`;
  const filepath = path.join(VAULT_PEOPLE_DIR, filename);

  const content = `---
title: "${target}"
date: ${date || new Date().toISOString().split("T")[0]}
tags:
  - person
  - deepscan
source: DeepScan v1.0
---

# ${target} — Intelligence Report

> Generated by DeepScan on ${date || new Date().toISOString().split("T")[0]}
> Source: \`localhost:3000\`

${rawText}
`;

  await writeFile(filepath, content, "utf-8");

  // Update INDEX.md if entry doesn't exist yet
  const indexContent = await readFile(VAULT_INDEX, "utf-8");
  const linkLine = `- [[people/${slug}|${target}]] — ${date || new Date().toISOString().split("T")[0]}`;

  if (!indexContent.includes(`people/${slug}`)) {
    await appendFile(VAULT_INDEX, `\n${linkLine}`, "utf-8");
  }

  return Response.json({ ok: true, path: filepath });
}
